# This workflow will install Python dependencies, run tests and lint with a
# single version of Python
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Install pylint
      run: pip install flake8 pytest

    - name: Lint Test with flake8
      run: |
        pylint $(git ls-files '*.py')

    - name: Test with pytest
      run: |
        pytest
